# Create full conda environment for development, including some useful tools
name: wrf_python_build
channels:
  - conda-forge
dependencies:
  - python
  - compilers
  - basemap
  - cartopy
  - jupyter
  - matplotlib
  - netcdf4
  - numpy
  - pycodestyle
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-googleanalytics
  - wrapt
  - xarray
  - python-build
  - pip
